# Application configuration
app:
  name: Playwright MCP Browser Agent
  version: 1.0.0
  environment: production

# Logging configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: logs/app.log
  max_size: 10485760  # 10MB
  backup_count: 5

# Browser configuration
browser:
  headless: false
  viewport:
    width: 1280
    height: 720
  timeout: 30000
  
# Task configuration
tasks:
  default_timeout: 300  # 5 minutes
  retry_count: 3
  retry_delay: 2

# Performance configuration
performance:
  max_concurrent_tasks: 3
  connection_pool_size: 5
  request_timeout: 60
